[package]
name = "mongoman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# mongodb = "2.1"
mongodb = "2.8.2"
bson = { version = "2", features = ["chrono-0_4"] } # Needed for using chrono datetime in doc
chrono = "0.4" # Used for setting DateTimes
tokio = "1"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
